development:
  clients:
    default:
      database: treestats-dev
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: treestats-test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
