development:
  sessions:
    default:
      database: treestats-dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: treestats-test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>